services:
  server:
    image: codeberg.org/forgejo/forgejo:11
    container_name: forgejo
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - FORGEJO__database__DB_TYPE=postgres
      - FORGEJO__database__HOST=IP:PORT
      - FORGEJO__database__NAME=forgejo-db1
      - FORGEJO__database__USER=admin
      - FORGEJO__database__PASSWD=PASSWORD
      - FORGEJO__database__SSL_MODE=disable
      # Optional: Additional database settings
      - FORGEJO__database__CHARSET=utf8
      - FORGEJO__database__MAX_IDLE_CONNS=10
      - FORGEJO__database__MAX_OPEN_CONNS=100
    restart: always
    networks:
      - forgejo
    volumes:
      - ./forgejo:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3100:3000"
      - "222:22"
    extra_hosts:
      - "host.docker.internal:host-gateway"  # For host database access

networks:
  forgejo:
    external: false